language: c

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env: COMPILER=clang

    - os: osx
      osx_image: xcode9.2
      env: COMPILER=clang

    - os: osx
      osx_image: xcode10.1
      env: COMPILER=gcc-8
      before_script:
        - brew link gcc

    - os: linux
      dist: xenial
      env: COMPILER=gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8

script:
  - $COMPILER --version
  - make clean && make CC=$COMPILER tree
  - ./bin/watermelon -d 2 -1
  - make clean && make CC=$COMPILER debug
  - ./bin/watermelon -d 10 -1
  - make clean && make CC=$COMPILER
  - ./bin/watermelon -d 12 -1
  - ./bin/watermelon -d 12 -j 2 -1
  - diff <(./tests/scripts/unit.sh tests/bin/perft 6 tests/data/general.dat)
    tests/logs/perft-general-6.log
  - diff <(./tests/scripts/unit.sh tests/bin/perft 7 tests/data/movegen.dat)
    tests/logs/perft-movegen-7.log
  - diff <(./tests/scripts/unit.sh tests/bin/perft 6 tests/data/canju.dat)
    tests/logs/perft-canju-6.log
  - diff <(./tests/scripts/unit.sh tests/bin/search 24 tests/data/canju.dat)
    tests/logs/search-canju.log
  - ./tests/bin/time 12
  - ./tests/bin/cubes './bin/watermelon -d 12 -q' './bin/watermelon -d 12 -q'
    '3a1kb2/2R3R2/3ab4/9/9/9/4cr3/4B4/4A4/2BAK4 r' || [ $? -eq 1 ]
