language: c

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env: COMPILER=clang

    - os: osx
      osx_image: xcode9.2
      env: COMPILER=clang

    - os: linux
      env: COMPILER=gcc-8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']

script:
  - make CC=$COMPILER && ./bin/watermelon 5
  - cd tests
  - diff <(./scripts/perft.sh 6 data/general.dat) logs/perft-general-6.log
  - diff <(./scripts/perft.sh 7 data/movegen.dat) logs/perft-movegen-7.log
  - diff <(./scripts/perft.sh 6 data/canju.dat) logs/perft-canju-6.log
