language: c

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env: COMPILER=clang

    - os: osx
      osx_image: xcode9.2
      env: COMPILER=clang

    - os: linux
      env: COMPILER=gcc-8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']

    - os: linux
      env: COMPILER=clang-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['clang-7', 'g++-7']

script:
  - make CC=$COMPILER && ./bin/watermelon 5
  - cd tests && ./scripts/perft.sh 6 data/fen.dat | tee ci-perft.dat
  - diff data/ref.dat ci-perft.dat
