language: c

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env: COMPILER=clang

    - os: osx
      osx_image: xcode9.2
      env: COMPILER=clang

    - os: linux
      env: COMPILER=gcc-8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-8']

script:
  - make CC=$COMPILER && ./bin/watermelon -d 5
  - diff <(./tests/scripts/unit.sh tests/bin/perft 6 tests/data/general.dat)
    tests/logs/perft-general-6.log
  - diff <(./tests/scripts/unit.sh tests/bin/perft 7 tests/data/movegen.dat)
    tests/logs/perft-movegen-7.log
  - diff <(./tests/scripts/unit.sh tests/bin/perft 6 tests/data/canju.dat)
    tests/logs/perft-canju-6.log
