
/* auto-generated by maskgen.py */
#ifndef MASKS_H
#define MASKS_H

#include "magics.h"

extern const __uint128_t BMASK;
extern const __uint128_t OMASK;

extern const __uint128_t PMASK[PADDED];

extern const __uint128_t UMASK[POINTS];
extern const __uint128_t LMASK[POINTS];
extern const __uint128_t RMASK[POINTS];
extern const __uint128_t FMASK[POINTS];

extern const __uint128_t JMASK[2];
extern const __uint128_t SMASK[2];
extern const __uint128_t XMASK[2];
extern const __uint128_t ZMASK[2];

#endif /* MASKS_H */
